name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - requests
    - rarfile
    - py7zr
    - pytorch_lightning
    - torch
    - torchvision
    - Pillow
    - opencv-python
	#if this cannot be used, use opencv-contrib-python